# Generated by Django 5.2.7 on 2025-12-14 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'doc', 'docx', 'txt', 'jpeg', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10485760)]),
        ),
    ]
