# Generated by Django 5.2.7 on 2025-12-16 03:50

import apps.attachments.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_attachment_checksum_alter_attachment_file_and_more'),
        ('comments', '0005_comment_visibility'),
        ('feedback', '0001_initial'),
        ('issues', '0004_alter_issue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=apps.attachments.storage.CustomAttachmentStorage(), upload_to='attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg', 'gif', 'webp', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['issue', 'created_at'], name='attachments_issue_i_30c338_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['comment', 'created_at'], name='attachments_comment_2975b7_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='attachments_uploade_565374_idx'),
        ),
    ]
