# Generated by Django 5.2.7 on 2025-12-18 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('issues', '0005_alter_issue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='converted_to',
        ),
        migrations.AddField(
            model_name='feedback',
            name='converted_to_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_source', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('converted', 'Converted to Issue'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
