# Generated by Django 5.2.7 on 2025-12-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options_remove_feedback_converted_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('new_feedback', 'New Feedback'), ('new_comment', 'New Comment'), ('assignment', 'Assignment'), ('status_change', 'Status Change'), ('mention', 'Mention'), ('feedback_converted', 'Feedback Converted')], default='new_feedback', max_length=20),
        ),
    ]
