# Generated by Django 5.2.7 on 2025-12-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='visibility',
        ),
    ]
