# Generated by Django 5.2.7 on 2025-12-11 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], default='excel', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('issues_by_status', 'Issues by Status'), ('issues_by_assignee', 'Issues by Assignee'), ('issues_by_priority', 'Issues by Priority'), ('feedback_summary', 'Feedback Summary'), ('team_performance', 'Team Performance'), ('resolution_analytics', 'Resolution Analytics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'status', 'created_at'], name='reports_rep_user_id_bc32d4_idx'),
        ),
    ]
