# Generated by Django 5.2.7 on 2025-12-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_options_report_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('issues_by_status', 'Issues by Status'), ('issues_by_assignee', 'Issues by Assignee'), ('issues_by_priority', 'Issues by Priority'), ('feedback_summary', 'Feedback Summary'), ('team_performance', 'Team Performance'), ('resolution_analytics', 'Resolution Analytics'), ('performance_dashboard', 'Performance Dashboard')], max_length=50),
        ),
    ]
