# Generated by Django 5.2.7 on 2026-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_format_alter_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True),
        ),
    ]
