# Generated by Django 5.2.7 on 2025-12-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_feedback', 'New Feedback'), ('new_comment', 'New Comment'), ('assignment', 'Assignment'), ('status_change', 'Status Change'), ('mention', 'Mention'), ('feedback_converted', 'Feedback Converted')], max_length=20),
        ),
    ]
