# Generated by Django 5.2.7 on 2025-12-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_feedback', 'New Feedback'), ('new_issue', 'New Issue'), ('new_comment', 'New Comment'), ('assignment', 'Assignment'), ('status_change', 'Status Change'), ('mention', 'Mention'), ('feedback_converted', 'Feedback Converted')], max_length=20),
        ),
    ]
